# config/routes.yaml

index:
    path: /
    controller: App\Controller\DefaultController::indexAction

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\DefaultController::number

logout:
    path: /logout